version: "3.9"

services:
  backend:
    build: ./backend
    container_name: backend_app
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 10s
      timeout: 3s
      retries: 3

  nginx:
    build: ./nginx
    container_name: nginx_proxy
    ports:
      - "80:80"
    depends_on:
      - backend   # без condition
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://backend:8080/health"]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 10s
    
networks:
  app_network:
    driver: bridge